Repository VariantSync/DiffDetective, pull requests merged in 2023-03, with the labels that each got.

#67 Treeification of Variation Diffs
  src/main/java/org/variantsync/diffdetective/diff/text/DiffLineNumberRange.java
  src/main/java/org/variantsync/diffdetective/mining/RunningExampleFinder.java
  src/main/java/org/variantsync/diffdetective/util/Assert.java
  src/main/java/org/variantsync/diffdetective/util/CSV.java
  src/main/java/org/variantsync/diffdetective/variation/diff/DiffGraph.java
  src/main/java/org/variantsync/diffdetective/variation/diff/DiffNode.java
  src/main/java/org/variantsync/diffdetective/variation/diff/DiffTree.java
  src/main/java/org/variantsync/diffdetective/variation/diff/DiffType.java
  src/main/java/org/variantsync/diffdetective/variation/diff/Projection.java
  src/main/java/org/variantsync/diffdetective/variation/diff/bad/BadVDiff.java
  src/main/java/org/variantsync/diffdetective/variation/diff/bad/BadVDiffFromDiffTreeSource.java
  src/main/java/org/variantsync/diffdetective/variation/diff/graph/FormalDiffGraph.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/DiffTreeParser.java
  src/main/java/org/variantsync/diffdetective/variation/diff/serialize/nodeformat/DiffNodeLabelPrettyfier.java
  src/main/java/org/variantsync/diffdetective/variation/diff/serialize/nodeformat/FormulasAndLineNumbersNodeFormat.java
  src/main/java/org/variantsync/diffdetective/variation/diff/serialize/nodeformat/FullNodeFormat.java
  src/main/java/org/variantsync/diffdetective/variation/diff/source/DiffTreeSource.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationNode.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTree.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTreeNode.java
  src/main/java/org/variantsync/diffdetective/variation/tree/source/VariationTreeSource.java
  src/test/java/BadVDiffTest.java
  src/test/java/StarfoldTest.java
  src/test/resources/badvdiff/1.diff
  src/test/resources/badvdiff/const.diff
  src/test/resources/badvdiff/deep_insertion.diff
  src/test/resources/badvdiff/diamond.diff
Labels: enhancement

#74 Refactorings for Analysis Running + Example Finding
  src/main/java/org/variantsync/diffdetective/AnalysisRunner.java
  src/main/java/org/variantsync/diffdetective/analysis/PreprocessingAnalysis.java
  src/main/java/org/variantsync/diffdetective/examplesearch/ExampleCriterions.java
  src/main/java/org/variantsync/diffdetective/examplesearch/ExampleFinder.java
  src/main/java/org/variantsync/diffdetective/examplesearch/Main.java
  src/main/java/org/variantsync/diffdetective/mining/DiffTreeMiner.java
  src/main/java/org/variantsync/diffdetective/mining/RunningExampleFinder.java
  src/main/java/org/variantsync/diffdetective/validation/EditClassValidation.java
  src/main/java/org/variantsync/diffdetective/validation/Validation.java
Labels: enhancement, Refactoring

#78 Parsing of Commits Without Parents (e.g., Initial Commit)
  src/main/java/org/variantsync/diffdetective/AnalysisRunner.java
  src/main/java/org/variantsync/diffdetective/datasets/DatasetFactory.java
  src/main/java/org/variantsync/diffdetective/datasets/ParseOptions.java
  src/main/java/org/variantsync/diffdetective/datasets/PatchDiffParseOptions.java
  src/main/java/org/variantsync/diffdetective/datasets/Repository.java
  src/main/java/org/variantsync/diffdetective/datasets/predefined/Marlin.java
  src/main/java/org/variantsync/diffdetective/datasets/predefined/StanciulescuMarlin.java
  src/main/java/org/variantsync/diffdetective/diff/git/CommitDiff.java
  src/main/java/org/variantsync/diffdetective/diff/git/DiffFilter.java
  src/main/java/org/variantsync/diffdetective/diff/git/GitDiffer.java
  src/main/java/org/variantsync/diffdetective/examplesearch/ExampleFinder.java
  src/main/java/org/variantsync/diffdetective/examplesearch/Main.java
  src/main/java/org/variantsync/diffdetective/internal/SimpleRenderer.java
  src/main/java/org/variantsync/diffdetective/mining/DiffTreeMiner.java
  src/main/java/org/variantsync/diffdetective/validation/EditClassValidation.java
  src/main/java/org/variantsync/diffdetective/variation/diff/DiffTree.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/DiffTreeParseOptions.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/DiffTreeParser.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTree.java
  src/test/java/BadVDiffTest.java
  src/test/java/DiffTreeParserTest.java
  src/test/java/EditClassesTest.java
  src/test/java/LinuxParsingTest.java
  src/test/java/MarlinDebug.java
  src/test/java/MoveDetectionTest.java
  src/test/java/PCTest.java
  src/test/java/PrintWorkingTreeDiff.java
  src/test/java/StarfoldTest.java
  src/test/java/TestLineNumbers.java
  src/test/java/TestMultiLineMacros.java
  src/test/java/TreeTransformersTest.java
Labels: enhancement

#84 Fix rename handling
  src/main/java/org/variantsync/diffdetective/diff/git/GitDiffer.java
  src/test/java/GitDifferTest.java
  src/test/resources/diffs/differ/.gitignore
  src/test/resources/diffs/differ/4a4c1db1b192e221d8e25460d6d1128d1bdd0c0d.lg
  src/test/resources/diffs/differ/a032346092e47048becb36a7cb183b4739547370.lg
  src/test/resources/diffs/differ/d7eeba1b94f3d0c0ebed3457eea8fa8537143348.lg
  src/test/resources/repos/.gitignore
  src/test/resources/repos/test-spl.zip
Labels: bug

#81 Run CI regardless of branch
  .github/workflows/maven.yml
Labels: bm_work

#85 Store exact line numbers for all lines
  src/main/java/org/variantsync/diffdetective/datasets/predefined/LinuxKernel.java
  src/main/java/org/variantsync/diffdetective/examplesearch/ExampleCriterions.java
  src/main/java/org/variantsync/diffdetective/feature/CPPAnnotationParser.java
  src/main/java/org/variantsync/diffdetective/variation/diff/DiffNode.java
  src/main/java/org/variantsync/diffdetective/variation/diff/Projection.java
  src/main/java/org/variantsync/diffdetective/variation/diff/bad/BadVDiff.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/DiffTreeParser.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/LogicalLine.java
  src/main/java/org/variantsync/diffdetective/variation/diff/serialize/nodeformat/DebugDiffNodeFormat.java
  src/main/java/org/variantsync/diffdetective/variation/diff/serialize/nodeformat/LabelOnlyDiffNodeFormat.java
  src/main/java/org/variantsync/diffdetective/variation/diff/serialize/nodeformat/ShowNodeFormat.java
  src/main/java/org/variantsync/diffdetective/variation/diff/transform/CollapseNestedNonEditedAnnotations.java
  src/main/java/org/variantsync/diffdetective/variation/diff/transform/NaiveMovedArtifactDetection.java
  src/main/java/org/variantsync/diffdetective/variation/diff/transform/Starfold.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationNode.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTreeNode.java
  src/test/java/EditClassesTest.java
  src/test/java/LinuxParsingTest.java
  src/test/java/PCTest.java
  src/test/java/TestLineNumbers.java
  src/test/resources/diffs/differ/a032346092e47048becb36a7cb183b4739547370.lg
  src/test/resources/diffs/parser/01_expected.lg
  src/test/resources/diffs/parser/02_expected.lg
  src/test/resources/diffs/parser/03_expected.lg
  src/test/resources/diffs/parser/04_expected.lg
  src/test/resources/diffs/parser/05_expected.lg
  src/test/resources/diffs/parser/08_expected.lg
  src/test/resources/diffs/parser/09_expected.lg
  src/test/resources/diffs/parser/10_expected.lg
  src/test/resources/diffs/parser/11_expected.lg
  src/test/resources/diffs/parser/12_expected.lg
  src/test/resources/diffs/parser/13_expected.lg
  src/test/resources/diffs/parser/14_expected.lg
  src/test/resources/diffs/parser/15_expected.lg
  src/test/resources/diffs/parser/16_expected.lg
  src/test/resources/diffs/parser/17_expected.lg
Labels: enhancement, bm_work

#83 Minor fixes and features
  src/main/java/org/variantsync/diffdetective/variation/diff/bad/BadVDiff.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationNode.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTree.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTreeNode.java
Labels: bug, enhancement
