Repository VariantSync/DiffDetective, pull requests merged in 2024-04, with the labels that each got.

#140 Add FSE'24 paper to README and some updates
  README.md
Labels: enhancement

#142 VariationTree::fromFile(Path)
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTree.java
Labels: enhancement

#135 Single source of truth for the DiffDetective version
  README.md
  default.nix
  pom.xml
  replication/esecfse22/Dockerfile
  replication/splc23-views/Dockerfile
  scripts/genUltimateResults.sh
  scripts/runValidation.sh
  scripts/runViewFeasibilityStudy.sh
  scripts/version.sh
Labels: Refactoring

#141 Release 2.2.0
  README.md
  default.nix
  nix/sources.json
  pom.xml
  replication/esecfse22/Dockerfile
  replication/splc23-views/Dockerfile
  scripts/genUltimateResults.sh
  scripts/runValidation.sh
  scripts/runViewFeasibilityStudy.sh
  scripts/version.sh
  src/main/antlr4/org/variantsync/diffdetective/feature/antlr/JPPExpression.g4
  src/main/java/org/variantsync/diffdetective/datasets/PatchDiffParseOptions.java
  src/main/java/org/variantsync/diffdetective/datasets/predefined/Marlin.java
  src/main/java/org/variantsync/diffdetective/datasets/predefined/MarlinCPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/examplesearch/ExampleFinder.java
  src/main/java/org/variantsync/diffdetective/feature/AbstractingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/AbstractingFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/AnnotationParser.java
  src/main/java/org/variantsync/diffdetective/feature/AnnotationType.java
  src/main/java/org/variantsync/diffdetective/feature/BooleanAbstraction.java
  src/main/java/org/variantsync/diffdetective/feature/CPPAnnotationParser.java
  src/main/java/org/variantsync/diffdetective/feature/CPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/ControllingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/DiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/ParseErrorListener.java
  src/main/java/org/variantsync/diffdetective/feature/PreprocessorAnnotationParser.java
  src/main/java/org/variantsync/diffdetective/feature/PropositionalFormulaParser.java
  src/main/java/org/variantsync/diffdetective/feature/cpp/AbstractingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/cpp/CPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/cpp/ControllingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/jpp/AbstractingJPPExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/jpp/JPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/internal/SimpleRenderer.java
  src/main/java/org/variantsync/diffdetective/variation/NodeType.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/VariationDiffParseOptions.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/VariationDiffParser.java
  src/main/java/org/variantsync/diffdetective/variation/tree/VariationTree.java
  src/test/java/CPPParserTest.java
  src/test/java/JPPParserTest.java
  src/test/java/PropositionalFormulaParserTest.java
  src/test/java/TestMultiLineMacros.java
  src/test/java/TreeDiffingTest.java
  src/test/resources/diffs/jpp/.gitignore
  src/test/resources/diffs/jpp/basic_jpp.diff
  src/test/resources/diffs/jpp/basic_jpp_expected.lg
Labels: bug, enhancement, release
