Repository VariantSync/DiffDetective, pull requests merged in 2024-03, with the labels that each got.

#134 feat: generic parsing interface and parsing of JavaPP annotations
  README.md
  default.nix
  pom.xml
  replication/esecfse22/Dockerfile
  replication/splc23-views/Dockerfile
  scripts/genUltimateResults.sh
  scripts/runValidation.sh
  scripts/runViewFeasibilityStudy.sh
  src/main/antlr4/org/variantsync/diffdetective/feature/antlr/JPPExpression.g4
  src/main/java/org/variantsync/diffdetective/datasets/PatchDiffParseOptions.java
  src/main/java/org/variantsync/diffdetective/datasets/predefined/Marlin.java
  src/main/java/org/variantsync/diffdetective/datasets/predefined/MarlinCPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/examplesearch/ExampleFinder.java
  src/main/java/org/variantsync/diffdetective/feature/AbstractingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/AbstractingFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/AnnotationParser.java
  src/main/java/org/variantsync/diffdetective/feature/AnnotationType.java
  src/main/java/org/variantsync/diffdetective/feature/BooleanAbstraction.java
  src/main/java/org/variantsync/diffdetective/feature/CPPAnnotationParser.java
  src/main/java/org/variantsync/diffdetective/feature/CPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/ControllingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/DiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/ParseErrorListener.java
  src/main/java/org/variantsync/diffdetective/feature/PreprocessorAnnotationParser.java
  src/main/java/org/variantsync/diffdetective/feature/PropositionalFormulaParser.java
  src/main/java/org/variantsync/diffdetective/feature/cpp/AbstractingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/cpp/CPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/feature/cpp/ControllingCExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/jpp/AbstractingJPPExpressionVisitor.java
  src/main/java/org/variantsync/diffdetective/feature/jpp/JPPDiffLineFormulaExtractor.java
  src/main/java/org/variantsync/diffdetective/internal/SimpleRenderer.java
  src/main/java/org/variantsync/diffdetective/variation/NodeType.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/VariationDiffParseOptions.java
  src/main/java/org/variantsync/diffdetective/variation/diff/parse/VariationDiffParser.java
  src/test/java/CPPParserTest.java
  src/test/java/JPPParserTest.java
  src/test/java/TestMultiLineMacros.java
  src/test/java/TreeDiffingTest.java
  src/test/resources/diffs/jpp/.gitignore
  src/test/resources/diffs/jpp/basic_jpp.diff
  src/test/resources/diffs/jpp/basic_jpp_expected.lg
Labels: enhancement, Refactoring

#137 Upgrade to Java 17
  default.nix
  local-maven-repo/deploy-functjonal.sh
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240129.202737-1.jar
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240129.202737-1.jar.md5
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240129.202737-1.jar.sha1
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240314.134555-1.jar
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240314.134555-1.jar.md5
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240314.134555-1.jar.sha1
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240314.134555-1.pom
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240314.134555-1.pom.md5
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/functjonal-1.0-20240314.134555-1.pom.sha1
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/maven-metadata.xml
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/maven-metadata.xml.md5
  local-maven-repo/org/variantsync/functjonal/1.0-SNAPSHOT/maven-metadata.xml.sha1
  local-maven-repo/org/variantsync/functjonal/maven-metadata.xml
  local-maven-repo/org/variantsync/functjonal/maven-metadata.xml.md5
  local-maven-repo/org/variantsync/functjonal/maven-metadata.xml.sha1
  pom.xml
Labels: bug, dependencies

#138 Hotfix: Potential crash when creating a snapshot of AnalysisResult
  src/main/java/org/variantsync/diffdetective/analysis/Analysis.java
  src/main/java/org/variantsync/diffdetective/analysis/AnalysisResult.java
Labels: bug

#132 Add PropositionalFormulaParserTest
  src/test/java/PropositionalFormulaParserTest.java
Labels: enhancement
